export const frustratedComments = [
  "Need a vacation and i want safari kind of thing or I'm starting \na trip on the vacation.",
  "A short trip turned into an unexpected 'wildlife tour'?",
  'In search of my happy place... \nAKA a mini-safari adventure.',
  "Should've bought a helicopter instead.",
  //   'Went for a drive, ended up on a parking safari.',
  //   'Is this the real life, \nor is this just a parking fantasy?',
  "If I had a dime for every spot taken, \nI'd own the car fleet.",
  //   'Did everyone else get the memo \nto park here today too?',
  'Brb, Even the shortest journey comes with scenic detours.',
  //   'I swear my car shrinks every time \nI look for a parking spot.',
  '5-minute drive? More like 5 minutes of driving,\n 30 minutes of admiring nature!',
  //   'Car for sale, comes with free parking spot.',
  'Taking the scenic route… even when I didn’t plan to!',
  "GPS says ‘arrived,’ but I think I just found a secret nature reserve!.",
  'I could’ve walked, but then I’d miss this unexpected wildlife crossing!.',
  'Who knew a short trip could come with so much adventure?.',
  "The road ahead is long, but so is the list of animals I might see!, \nI'm still amused by nature!.",
  //   "Why don't they make parking spots like they used to?",
  'Next stop: wherever the adventure takes me., \ntake pictures.',
  'Every mile brings a new surprise—nature doesn’t disappoint!',

  "The best kind of traffic jam? A herd of elephants crossing! \n'Miles away from home, but right in the heart of adventure'.",
  //   'At this point, I might as well park in Narnia.',
  'Safari mode: ON. Destination: Unknown.?',
  'They said it’s a long drive, but have you seen these views? \nIf road trips had a soundtrack, mine would be the sound of the wild..',
  //   'Maybe if I play musical chairs with my car, \na spot will open up.',
  'Is there a cheat code for instant parking?',
  'Meeting? Haha. I havent even found a parking.',
  "I didn't sign up for this episode of \n'Parking Spot Wars'.",
  "Honey, I'll be late. \nI'm stuck in a parking saga.",
  "I'm sure my car is enjoying this \ntour of the parking lot.",
  'One does not simply park in a \nbustling city.',
  //   "If parking were an Olympic sport, \nI'd have a gold medal by now.",
  "Who needs a gym when you've got \na parking lot workout?",
  //   "Dear parking lot, why can't \nwe just find a space?",
  //   'The real Bermuda Triangle is this parking lot.',
  //   "My car's favorite pastime? \nHide and seek.",
  //   "I feel like a knight, but instead of a dragon, \nI'm hunting for a parking spot.",
  "This isn't parking, \nit's car hide-and-seek!",
  "I didn't choose the parking life. \nThe parking life chose me.",
  //   'Is it just me, or are parking spaces \ngetting slimmer these days?',
  'Pardon me while I park my car in another timezone.',
  //   "Where's a parking fairy when you need one?",
  'Parking: The ultimate test of patience.',
  'One small step for man, \none giant leap to find a parking spot.',
  //   'Did anyone tell the parking spaces \nthat hide and seek time is over?',
  'Time for my daily game of \nSpot the Parking Spot.',
  //   "I remember the days when \nthe hardest maze was in a children's menu.",
  "Accepting bets on whether \nI'll find a spot first, or retire.",
  "If I had a penny for every minute \nI've spent looking for parking, \nI'd be a millionaire.",
  "My GPS says 'you have reached your destination', \nbut where's the parking?!",
  "I've circled so much, \nI'm getting dizzy. \nWhere's that parking spot?",

  'I wonder if my car gets as tired as \nI do searching for a spot.',
  "Looking for parking is my car's \nfavorite cardio workout.",
  "One day, I'll tell my grandkids about \nthe great parking lot odyssey.",
  'I think I just saw a tumbleweed roll by…',
  'Siri, find me the nearest parking spot, \nplease!',
  //   "Maybe I should have listened when they said 'don't forget where you parked'.",
  'Time to play my least favorite game: \nparking lot roulette.',
  //   'Anyone got a magic wand? I need to conjure a parking spot.',
  "I've got 99 problems, \nand parking is all of them.",
  'I swear, the parking spots are playing \nmusical chairs without me.',
  "If I spend any longer searching, \nI'm going to need to refuel.",
  'Thinking about adopting a homing pigeon \nto find parking spots for me.',
  //   'Parking lots: the adult version of a maze.',
  //   'Does anyone have the number for the parking spot hotline?',
  //   "When they said 'park it like it's hot', I didn't think they meant 'in the sun because you couldn't find a spot'.",
  //   "They see me rollin', they hatin', patrolling, and I'm still trying to find parking.",
  "There's no 'I' in 'safari', \nbut there is an 'I' in 'circle \nthe subscription for the fifth time'.",
  //   'Did I miss the memo about national occupy a parking space day?',
  'I bet even Columbus found America faster \nthan I can find a parking spot.',
  //   "Should've left breadcrumbs from the last parking spot I found.",
  "If I park any further away, \nI'll be in the next town over.",
  "Guess it's time for my daily game of \nparking spot bingo.",
  'Wanted: a magic carpet, \nbecause Aladdin never had parking issues.',
  //   "If finding parking was a video game, I'd be on the hardest level.",
  //   "My car is on a diet - it's been circling the parking lot for hours.",
  "Guess who's going on an \nunexpected parking safari!",
  //   'Is there a parking space whisperer in the house?',
  'Parking lots are just adult versions \nof musical chairs.',
  'Did all the parking spaces go on \nvacation or something?',
  "There are two types of people: \nthose who find parking, \nand those who don't. \nGuess which one I am.",

  "Park anywhere, they said. \nIt'll be easy, they said.",

  "I've seen unicorns, \nthe Loch Ness monster, \nbut a free parking spot? Never.",

  `"Siri, find me the nearest ride for a short safari, please!" \nSiri: "Hmm, there's a spot 200 miles away. Ready for a road trip?"`,
]

export const getRamdomComment = () =>
  frustratedComments[Math.floor(Math.random() * frustratedComments.length)]
